### ISSUE TITLE
Layout for AlexNet and VGGNetD not working

### ISSUE THREAD

**Issue by DanPederEriksen** [deeplearning4j/dl4j-model-z#11]
The network layouts is not possible to instanciate. 

AlexNet:
new AlexNet(28, 78, 1, 65, 123, 1).init();

Result:
Exception in thread "main" org.deeplearning4j.nn.conf.inputs.InvalidInputTypeException: Invalid input: activations into layer are h=2 but kernel size is 3 with padding 0
	at org.deeplearning4j.nn.layers.convolution.KernelValidationUtil.validateShapes(KernelValidationUtil.java:19)
	at org.deeplearning4j.nn.conf.layers.setup.ConvolutionLayerSetup.getConvolutionOutputSize(ConvolutionLayerSetup.java:427)
	at org.deeplearning4j.nn.conf.layers.setup.ConvolutionLayerSetup.updateLayerInputs(ConvolutionLayerSetup.java:175)
	at org.deeplearning4j.nn.conf.layers.setup.ConvolutionLayerSetup.<init>(ConvolutionLayerSetup.java:98)
	at org.deeplearning4j.nn.conf.MultiLayerConfiguration$Builder.build(MultiLayerConfiguration.java:441)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$ListBuilder.build(NeuralNetConfiguration.java:255)
	at org.deeplearning4j.AlexNet.conf(AlexNet.java:111)
	at org.deeplearning4j.AlexNet.init(AlexNet.java:117)

VGGNetD:
new VGGNetD(28, 78, 1, 65, 123, 1, null).init();

Result:
Exception in thread "main" org.deeplearning4j.nn.conf.inputs.InvalidInputTypeException: Invalid input: activations into layer are h=1 but kernel size is 2 with padding 0
	at org.deeplearning4j.nn.layers.convolution.KernelValidationUtil.validateShapes(KernelValidationUtil.java:19)
	at org.deeplearning4j.nn.conf.layers.setup.ConvolutionLayerSetup.getConvolutionOutputSize(ConvolutionLayerSetup.java:427)
	at org.deeplearning4j.nn.conf.layers.setup.ConvolutionLayerSetup.updateLayerInputs(ConvolutionLayerSetup.java:175)
	at org.deeplearning4j.nn.conf.layers.setup.ConvolutionLayerSetup.<init>(ConvolutionLayerSetup.java:98)
	at org.deeplearning4j.nn.conf.MultiLayerConfiguration$Builder.build(MultiLayerConfiguration.java:441)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$ListBuilder.build(NeuralNetConfiguration.java:255)
	at org.deeplearning4j.VGGNetD.conf(VGGNetD.java:157)
	at org.deeplearning4j.VGGNetD.init(VGGNetD.java:161)
	at org.deeplearning4j.VGGNetD.main(VGGNetD.java:171)

**Comment by DanPederEriksen** [comment]
The networks needs larger images to work.
