### ISSUE TITLE
caffeInitQuick model not working from CifarModelVariations.java

### ISSUE THREAD

**Issue by Vinay13389** [deeplearning4j/dl4j-model-z#7]
As per our talk with Adam i created this issue.

i used  below configuration 
 int nOut[]={32,32,64,64};
 CifarModelVariations cifarmodelVariation = new CifarModelVariations(32,
                                                       32,
                                                       3,
                                                       10,
                                                       123,
                                                       1,
                                                       3,
                                                       nOut,
                                                       "relu",
                                                       WeightInit.DISTRIBUTION,
                                                       OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT,
                                                       Updater.NESTEROVS,
                                                       LossFunctions.LossFunction.NEGATIVELOGLIKELIHOOD,
                                                       0.01,
                                                       0.0,
                                                       true,
                                                       0.02,
                                                       0.9);

the above configuration gives me below error

Exception in thread "main" org.deeplearning4j.nn.conf.inputs.InvalidInputTypeException: Invalid input: activations into layer are w=1 but kernel size is 3 with padding 0

at org.deeplearning4j.nn.layers.convolution.KernelValidationUtil.validateShapes(KernelValidationUtil.java:23)
	at org.deeplearning4j.nn.conf.layers.setup.ConvolutionLayerSetup.getConvolutionOutputSize(ConvolutionLayerSetup.java:418)
	at org.deeplearning4j.nn.conf.layers.setup.ConvolutionLayerSetup.updateLayerInputs(ConvolutionLayerSetup.java:163)
	at org.deeplearning4j.nn.conf.layers.setup.ConvolutionLayerSetup.<init>(ConvolutionLayerSetup.java:86)
	at org.deeplearning4j.nn.conf.MultiLayerConfiguration$Builder.build(MultiLayerConfiguration.java:292)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$ListBuilder.build(NeuralNetConfiguration.java:211)
	at org.deeplearning4j.examples.convolution.CifarModelVariations.caffeInitQuick(CifarModelVariations.java:180)
	at org.deeplearning4j.examples.convolution.CifarModelVariations.buildNetwork(CifarModelVariations.java:410)
	at org.deeplearning4j.examples.convolution.Cifar.main(Cifar.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by crockpotveggies** [comment]
Apologies for being 2 years late on this, but we've migrated the zoo to the main deeplearning4j project https://github.com/deeplearning4j/deeplearning4j
